/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>
#include "gpio_driver.h"

#define ui32 uint32_t

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void){
	for(volatile ui32 i = 0; i < 500000; i++);
}

GPIO_Handle_t LedBlue, LedRed, LedOrange, LedGreen, Button;

void initLeds(){
	GPIO_PeriClockControl(RCC_PORTD, ENABLE);
	GPIO_OutputPinFactory(&LedRed, GPIO_PIN_NO_14);
	GPIO_OutputPinFactory(&LedBlue, GPIO_PIN_NO_15);
	GPIO_OutputPinFactory(&LedGreen, GPIO_PIN_NO_12);
	GPIO_OutputPinFactory(&LedOrange, GPIO_PIN_NO_13);
}

void toggleLeds(){
	GPIO_ToggleOutputHandler(&LedBlue);
	GPIO_ToggleOutputHandler(&LedGreen);
	delay();
	GPIO_ToggleOutputHandler(&LedRed);
	GPIO_ToggleOutputHandler(&LedOrange);
}

void initButton(){
	Button.pGPIOx = GPIOA;
	Button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	Button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	Button.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_PeriClockControl(RCC_PORTA, ENABLE);
	GPIO_Init(&Button);
}

uint8_t flag = 0;

int main(void)
{
	initLeds();
	initButton();

    while(1){
    	if(flag){
    		toggleLeds();
    	}
    }
}

void EXTI0_IRQHandler(void){
	GPIO_IRQHandling(GPIO_PIN_NO_0);
	flag  = !flag;
}
