/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>

#define ui32 uint32_t
#define RCC_BASE 0x40023800U
#define RCC_PORTD_OFFSET 0x30U
#define RCC_ENABLE_PORTD RCC_BASE + RCC_PORTD_OFFSET

#include "gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void){
	for(volatile ui32 i = 0; i < 500000; i++);
}

void GpioOutputPinFactory(GPIO_Handle_t *pGPIOHandle, uint8_t pinNumber){
	pGPIOHandle->pGPIOx = GPIOD;
	pGPIOHandle->GPIO_PinConfig.GPIO_PinNumber = pinNumber;
	pGPIOHandle->GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pGPIOHandle->GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	pGPIOHandle->GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	pGPIOHandle->GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_Init(pGPIOHandle);
}

GPIO_Handle_t LedBlue, LedRed, LedOrange, LedGreen;

void initLeds(){
	GPIO_PeriClockControl(RCC_PORTD, ENABLE);
	GPIO_OutputPinFactory(&LedRed, GPIO_PIN_NO_14);
	GPIO_OutputPinFactory(&LedBlue, GPIO_PIN_NO_15);
	GPIO_OutputPinFactory(&LedGreen, GPIO_PIN_NO_12);
	GPIO_OutputPinFactory(&LedOrange, GPIO_PIN_NO_13);
}

void toggleLeds(){
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);

	delay();

	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
}

int main(void)
{
	initLeds();

    while(1){
    	toggleLeds();
    }
}
