/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>

#define ui32 uint32_t
#define RCC_BASE 0x40023800U
#define RCC_PORTD_OFFSET 0x30U
#define RCC_ENABLE_PORTD RCC_BASE + RCC_PORTD_OFFSET

#include "gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void){
	for(volatile ui32 i = 0; i < 500000; i++);
}

void GpioOutputPinFactory(GPIO_Handle_t *GpioLed, uint8_t pinNumber){
	GpioLed->pGPIOx = GPIOD;
	GpioLed->GPIO_PinConfig.GPIO_PinNumber = pinNumber;
	GpioLed->GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed->GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GpioLed->GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed->GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
}

int main(void)
{
	//*((volatile ui32*) (RCC_ENABLE_PORTD)) |= (1 << 3);		//enable rcc on port d
	GPIO_PeriClockControl(RCC_PORTD, ENABLE);
	GPIO_Handle_t LedBlue, LedRed, LedOrange, LedGreen;
	GpioOutputPinFactory(&LedRed, GPIO_PIN_NO_14);
	GpioOutputPinFactory(&LedBlue, GPIO_PIN_NO_15);
	GpioOutputPinFactory(&LedGreen, GPIO_PIN_NO_12);
	GpioOutputPinFactory(&LedOrange, GPIO_PIN_NO_13);

	GPIO_Init(&LedBlue);
	GPIO_Init(&LedRed);
	GPIO_Init(&LedGreen);
	GPIO_Init(&LedOrange);

    while(1){
    	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
    	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);

    	delay();

    	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
    	GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
    }
}
